- name: Get Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
    dest: ~/.
    mode: a+x

- name: Install Minikube
  become: yes
  dnf:
    name: "{{ ansible_facts['env']['HOME'] }}/minikube-latest.x86_64.rpm"
    disable_gpg_check: yes
    state: present