- name: Upgrade system
  become: yes
  dnf:
    name: "*"
    state: latest

- name: Autoremove unneeded packages installed as dependencies
  become: yes
  dnf:
    autoremove: yes

- name: Packages
  become: yes
  dnf:
    name:
      # - "@Virtualization Host"
      - virt-install
      - virt-viewer
      - make
    state: latest

- name: Modules
  become: yes
  dnf:
    name:
      - "@virt:ol"
    state: present

- name: Start libvirt module
  become: yes
  ansible.builtin.systemd:
    name: libvirtd
    enabled: yes
    state: started